language: python
cache: pip
os:
- linux
python:
- '3.8'
install:
- pip install -r requirements.txt
- pip install -r requirements_rtd.txt
- pip install pytest
- pip install .
script:
- python -m pytest --ignore=doc/
- cd doc
- make html
