name: Test on Ubuntu

on:
  pull_request:
      branches: [main]
      types: [synchronize, opened, reopened]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Tools
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
        pip install .
    - name: Pytest
      run: |
        pytest tests/
