name: Test on Ubuntu

on:
  pull_request:
      branches: [main]
      types: [synchronize, opened, reopened]
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Daily at noon UTC


jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Pytest
      run: |
        pytest tests/
