name: Test on Ubuntu

on:
  pull_request:
      branches: [main]
      types: [synchronize, opened, reopened]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Pytest
      run: |
        pytest --cov=./probeinterface/ --cov-report xml:./coverage.xml tests/ 
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        file: ./coverage.xml
        flags: unittests
